Updated spanner emulator version
cloudspannerecosystem/harbourbridge pull request #211
Opened 2021-11-02 14:54 UTC by Deep1998

Fixes #<issue_number_goes_here>

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2021-11-02 16:01 UTC, Deep1998 commented
Latest emulator image does not support json yet.

2021-11-26 11:43 UTC, Deep1998 commented
ETA: Dec 21

2022-01-05 11:01 UTC, Deep1998 commented on testing/mysql/integration_test.go
> +	if json {
skip json checks for interleaved table test since that uses a different dump.

2022-01-05 17:07 UTC, bharadwaj-aditya requested changes

2022-01-06 11:33 UTC, bharadwaj-aditya approved these changes
LGTM

2022-01-06 11:35 UTC, merged